/**
 * Goal of RecipeParser.java:
 * 
 * This should parse the recipes generated from the GPT response and convert it
 *  into strings, into MongoDB . Ideally, this should be called when we press 
 * "save recipe" after create it and already shouldnt have duplicates
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class RecipeParser {
    private String TITLE;
    private ArrayList<String> INGREDIENTS = new ArrayList<>();
    private String ingredients = "Ingredients: \n";
    private ArrayList<String> STEPS = new ArrayList<>();
    private String steps = "Steps: \n";
    private static final String RECIPE_FILE = "./recipe.txt";

    // getter methods for private variables
    public String getTitle() {
        return TITLE;
    }
    public ArrayList<String> getIngredients() {
        return INGREDIENTS;
    }
    public ArrayList<String> getSteps() {
        return STEPS;
    }
    public String getStringSteps() {
        return steps;
    }
    public String getStringIngredients() {
        return ingredients;
    }

    /**
     * Parses through ChatGPT generated messages and gets recipe title, ingredients, and steps
     * @throws IOException
     * @throws InterruptedException
     */
    public void parse() throws IOException, InterruptedException {
        System.out.println("PARSING");
        FileReader fr
        = new FileReader(RECIPE_FILE); // reads recipes text generated by RecipeCreator
        BufferedReader br = new BufferedReader(fr);

        while (br.ready()) {
            String line = br.readLine();
            if (!line.isEmpty()){ // checks for non-empty line
                char first = line.charAt(0);
                switch(first) {
                    case 'T': // Title
                        TITLE = line.substring(7); // start of recipe title
                        break;
                    case '-': // Ingredients
                        //line = line.substring(1); // gets rid of dash
                        first = line.charAt(0); // check for space
                        if (first == ' ') {
                            line = line.substring(1); // gets rid of space
                        }
                        ingredients += line + "\n";
                        break;
                    case '#': // Steps
                        line = line.substring(3); // start of step
                        steps += line + "\n";
                }
            }   
        }
        System.out.println("Inserting recipe...");
        RecipeManager.insertRecipe(TITLE, ingredients, steps);
        br.close();
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        RecipeParser parser = new RecipeParser();
        //System.out.println("HELLO");
        parser.parse();
    }
}
